name: Bot Chill Auto
on:
  schedule:
    - cron: '30 17 * * *' # Se lance Ã  18h30 pour les matchs du soir
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python chill.py
