name: Bot Soiree Automatique
on:
  schedule:
    - cron: '0 17 * * *'  # Se lance seul à 18h00 (Heure FR)
    - cron: '0 19 * * *'  # Se lance seul à 20h00 (Heure FR)
  workflow_dispatch:      # Pour pouvoir le lancer à la main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python chill.py
